title = "Nandu Prasad"
baseURL = "https://nandu26m.github.io/"
languageCode = "en-us"
theme = "ananke"
#themesDir = "../.."

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
canonifyURLs = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = ""
  facebook = "https://www.facebook.com/nandu.prasad.56808"
  twitter = ""
  instagram = "https://www.instagram.com/nanduprasad_/"
  youtube = ""
  github = "https://github.com/nandu26m"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/nandu-prasad-56045716b"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/pexels-jakub-novacek-924824.jpg"
  recent_posts_number = 3
